services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - whatsapp_node_modules:/app/node_modules
    command: npm run dev

volumes:
  whatsapp_node_modules: