import { validationResult } from "express-validator";

/**
 * Middleware to check if any validation errors
 * were generated by express-validator.
 */
export const validateRequest = (req, res, next) => {
  // Extract validation errors from the request
  const errors = validationResult(req);

  // If there are validation errors, send a 400 response
  if (!errors.isEmpty()) {
    return res.status(400).json({
      message: "Validation failed",

      // Returns an array of all validation errors
      errors: errors.array(),
    });
  }

  // No validation errors, move to the next middleware/controller
  next();
};